<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260413102500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create applications table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE applications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(20) NOT NULL, city VARCHAR(255) NOT NULL, how_did_your_hear_about_us TEXT DEFAULT NULL, home_type VARCHAR(255) DEFAULT NULL, space_setup TEXT DEFAULT NULL, fireplace_unit VARCHAR(255) DEFAULT NULL, finish_wanted VARCHAR(255) DEFAULT NULL, space_photo TEXT DEFAULT NULL, additional_notes TEXT NOT NULL, PRIMARY KEY(id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE applications');
    }
}
