<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260418034000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add project type fields to applications and create typed project details tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("ALTER TABLE applications ADD project_type VARCHAR(255) DEFAULT 'Media Wall' NOT NULL");
        $this->addSql('ALTER TABLE applications ADD preferred_start_time VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE applications ADD budget_range VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE applications ADD owns_property BOOLEAN DEFAULT NULL');

        $this->addSql('CREATE TABLE application_basement_details (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, details JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3B60D4D6E03061CE ON application_basement_details (application_id)');
        $this->addSql('ALTER TABLE application_basement_details ADD CONSTRAINT FK_3B60D4D6E03061CE FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE application_bathroom_details (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, details JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4FAF5472E03061CE ON application_bathroom_details (application_id)');
        $this->addSql('ALTER TABLE application_bathroom_details ADD CONSTRAINT FK_4FAF5472E03061CE FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE application_kitchen_details (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, application_id INT NOT NULL, details JSON NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4A67FA8E03061CE ON application_kitchen_details (application_id)');
        $this->addSql('ALTER TABLE application_kitchen_details ADD CONSTRAINT FK_A4A67FA8E03061CE FOREIGN KEY (application_id) REFERENCES applications (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE application_basement_details DROP CONSTRAINT FK_3B60D4D6E03061CE');
        $this->addSql('ALTER TABLE application_bathroom_details DROP CONSTRAINT FK_4FAF5472E03061CE');
        $this->addSql('ALTER TABLE application_kitchen_details DROP CONSTRAINT FK_A4A67FA8E03061CE');

        $this->addSql('DROP TABLE application_basement_details');
        $this->addSql('DROP TABLE application_bathroom_details');
        $this->addSql('DROP TABLE application_kitchen_details');

        $this->addSql('ALTER TABLE applications DROP project_type');
        $this->addSql('ALTER TABLE applications DROP preferred_start_time');
        $this->addSql('ALTER TABLE applications DROP budget_range');
        $this->addSql('ALTER TABLE applications DROP owns_property');
    }
}
